### PR TITLE
Hides dock icon

### PR DESCRIPTION
**Pull request by Naoto-Ida**
This hides the dock icon.

### CODE REVIEW

**Comment by jmaciasluque** [comment]
Please accept this, or implement this logic.

**Comment by paulyoung** [comment]
This was intentionally removed in 866ba06c5aa1b1c8c68b50e3f1a4e3209d89e978 as a result of #11.

**Comment by paulyoung** [comment]
Thanks @Naoto-Ida! This should now be unnecessary as a result of merging #15, so I'm going to close this.

**Comment by jmaciasluque** [comment]
:+1: Cheers.

**Comment by Naoto-Ida** [comment]
Cool.

**Pull request closed without merging**
