### PR TITLE
added hide icon from application switcher and dock by default

### PR DESCRIPTION
**Pull request by gatopanx**

### CODE REVIEW

**Comment by z3t0** [comment]
Why not just use 

```
<key>LSUIElement</key>
<true/>
```

**Comment by ValentinBrclz** [comment]
This is directly linked with #21

**Comment by ngoctnq** [comment]
this has one minor problem: it hides the icon, but the preference is still set otherwise, hence on the task bar the option still says "Hide Dock icon."

**Comment by luki-** [comment]
Guys, any chance to merge this PR? :)
Ping @paulyoung @gatopan

**Comment by sphvn** [comment]
Need to change the default behaviour of the menu item for "Hide Dock Icon" for this to be alright I think.

**Comment by paulyoung** [comment]
I think this PR is incomplete and it's been a while without a response, so I'm going to close for now. 

Also, I think this is probably better managed with user defaults / #21.

Thanks for the suggestion!

**Pull request closed without merging**
