### PR TITLE
Change format to Artist - Title

### PR DESCRIPTION
**Pull request by cahalane**
This is just something that's been bothering me slightly. Artist - Title is a standard format for writing song titles, Statusfy doesn't use this format.

### CODE REVIEW

**Review by jonnyom — APPROVED** [review]
Please merge

**Comment by sphvn** [comment]
Standard for what? Even spotify itself is usually Title - Artist, albeit on a new line.

**Comment by cahalane** [comment]
The newline makes it a completely different thing. Generally speaking, people have always written Artist - Track when writing a track on one line, because that's what generally feels natural, same way as we don't write `subfolder/folder/root`.

Good example: YouTube music video titles:
screenshot 2017-10-10 10 15 37

I can't find a specific style-guide for reporting or describing music, but Artist - Title is specified in the style-guide of the [piracy scene](https://scenerules.org/t.html?id=riaa2014_4.1.nfo), if that means anything.

**Comment by sphvn** [comment]
Solid reply. 👍 from me.

**Comment by akrabat** [comment]
FWiW, I disagree. When I'm looking at Statusfy, I want to know the name of the song primarily and then may be the artist's name, so I think the current order is correct.

In Spotify, it's always title, then artist:

screen shot 2017-12-22 at 09 37 01

screen shot 2017-12-22 at 09 38 05

Same for iTunes:

screen shot 2017-12-22 at 09 40 51

**Comment by samaero** [comment]
I agree that it should remain as Title - Artist. Currently, when two tracks by the same artist play back to back, there’s minimal jumping around of the text; if it were to change to Artist - Title, all of the text would jump after every song change. It’s nitpicky but I think it’s cleaner this way.

**Comment by paulyoung** [comment]
This isn't something I'd like to change, but thanks for the suggestion.

**Pull request closed without merging**
